import io
import os

import pandas as pd
import resend
from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from openai import OpenAI
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address
 
load_dotenv()
 
limiter = Limiter(key_func=get_remote_address)
 
app = FastAPI(
    title="Sales Insight Automator",
    description="Upload a CSV/Excel sales file → get an AI summary emailed instantly.",
    version="1.0.0",
)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
 
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        os.getenv("FRONTEND_URL", "*"),
    ],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ── Clients ───────────────────────────────────────────────
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
resend.api_key = os.getenv("RESEND_API_KEY")


# ── Routes ────────────────────────────────────────────────

@app.get("/health", tags=["System"])
def health_check():
    """Health check endpoint for Docker and Render."""
    return {"status": "ok", "service": "Sales Insight Automator"}


@app.post("/api/analyze", tags=["Analysis"])
@limiter.limit("5/minute")
async def analyze_sales(
    request: Request,
    file: UploadFile = File(..., description="CSV or Excel sales data file (max 5MB)"),
    email: str = Form(..., description="Recipient email address for the AI summary"),
):
    """
    Upload a .csv or .xlsx sales file and provide a recipient email.
    The API will:
    1. Parse the file
    2. Generate an executive AI summary via OpenAI gpt-4o-mini
    3. Email the summary using Resend
    """

    # ── 1. Validate file type ──────────────────────────────
    allowed = (".csv", ".xlsx")
    if not file.filename.endswith(allowed):
        raise HTTPException(
            status_code=400,
            detail="Invalid file type. Only .csv and .xlsx are accepted.",
        )

    # ── 2. Read and size-check ─────────────────────────────
    contents = await file.read()
    if len(contents) > 5 * 1024 * 1024:
        raise HTTPException(status_code=400, detail="File too large. Maximum size is 5MB.")

    # ── 3. Parse with pandas ───────────────────────────────
    try:
        if file.filename.endswith(".csv"):
            df = pd.read_csv(io.BytesIO(contents))
        else:
            df = pd.read_excel(io.BytesIO(contents))
    except Exception:
        raise HTTPException(status_code=400, detail="Could not parse the file. Ensure it is valid.")

    if df.empty:
        raise HTTPException(status_code=400, detail="The uploaded file contains no data.")

    # ── 4. Build a clean data snapshot for the LLM ────────
    row_count = len(df)
    col_summary = df.dtypes.to_string()
    data_preview = df.to_string(index=False, max_rows=100)

    prompt = f"""You are a senior business analyst at Rabbitt AI.
Analyze the sales data below and produce a professional executive summary (4–6 paragraphs).

Cover:
- Overall performance and revenue highlights
- Top performing regions and product categories
- Any anomalies or concerning trends (e.g. cancellations)
- Month-over-month patterns if dates are present
- 2–3 specific, actionable strategic recommendations

Dataset info: {row_count} rows, columns: {col_summary}

Sales Data:
{data_preview}

Write in a confident, executive-ready tone. No bullet points — use flowing paragraphs."""

    # ── 5. Call OpenAI gpt-4o-mini ─────────────────────────
    try:
        completion = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1200,
            temperature=0.4,
        )
        ai_summary = completion.choices[0].message.content
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"OpenAI error: {str(e)}")

    # ── 6. Send email via Resend ───────────────────────────
    html_body = f"""
    <div style="font-family:'Segoe UI',sans-serif;max-width:640px;margin:auto;padding:2rem;background:#f9f9f9;">
      <div style="background:#1a1a2e;padding:1.5rem 2rem;border-radius:12px 12px 0 0;">
        <h1 style="color:#e0e0ff;margin:0;font-size:1.4rem;">📊 Sales Insight Summary</h1>
        <p style="color:#888;margin:0.3rem 0 0;font-size:0.85rem;">Generated by Rabbitt AI · Sales Automator</p>
      </div>
      <div style="background:#fff;padding:2rem;border-radius:0 0 12px 12px;border:1px solid #e0e0e0;line-height:1.8;color:#333;font-size:0.95rem;">
        {ai_summary.replace(chr(10), '<br/>')}
      </div>
      <p style="text-align:center;color:#bbb;font-size:0.75rem;margin-top:1rem;">Rabbitt AI · Confidential · Do not forward</p>
    </div>
    """

    try:
        resend.Emails.send({
            "from": "onboarding@resend.dev",  # ← change to your verified domain later
            "to": email,
            "subject": "📊 Q1 Sales Insight Summary — Rabbitt AI",
            "html": html_body,
        })
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Email error: {str(e)}")

    return {
        "message": "Summary generated and sent successfully!",
        "recipient": email,
        "preview": ai_summary[:400] + "...",
    }